# Generated by Django 4.0.4 on 2022-06-13 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Номер в гостевом доме', 'Номер в гостевом доме'), ('Квартира', 'Квартира'), ('Частный дом', 'Частный дом'), ('Номер в гостинице', 'Номер в гостинице')], max_length=250, verbose_name='Тип')),
                ('rooms', models.IntegerField(verbose_name='Кол-во комнат')),
                ('bedrooms', models.IntegerField(verbose_name='Кол-во спален')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('region', models.CharField(choices=[('Краснодарский край', 'Краснодарский край'), ('Крым', 'Крым'), ('Кавказ', 'Кавказ'), ('Центральная Россия', 'Центральная Россия'), ('Сибирь', 'Сибирь'), ('Дальний восток', 'Дальний восток'), ('Урал', 'Урал')], max_length=250, verbose_name='Регион')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('detail', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Подробности')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=17, null=True, verbose_name='Номер телефона')),
                ('passport', models.CharField(blank=True, max_length=15, null=True, verbose_name='Паспортные данные')),
                ('id_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профиль пользователя',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Ссылка на изображение')),
                ('id_realty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='booking.realty', verbose_name='id недвижимости')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('amount_commission', models.IntegerField(verbose_name='Цена с комиссией')),
                ('amount', models.IntegerField(verbose_name='Цена без комиссии')),
                ('id_realty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realty', to='booking.realty', verbose_name='Недвижимость')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
                'ordering': ['-date_creation'],
            },
        ),
    ]
